church_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout
from django.contrib import messages
from django.shortcuts import redirect

def custom_logout(request):
    logout(request)
    messages.success(request, f'You have successfully been logged out!')
    return redirect('home_page')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('members.urls')),
    path('register/', user_views.register, name = 'register'),
    path('member/register/', user_views.member_account, name = 'register_member'),
    path('member/login/', user_views.member_login, name = 'member_login'),
    path('user/login/', user_views.user_login, name = 'user_login'),
    path('logout/', custom_logout, name = 'logout'),
    path('contributions/', include('contributions.urls')),
    path('children/', include('children.urls')),
]

members/urls.py
from django.urls import path
from .views import (MembersListView,
                     MembersDetailView,
                     MembersCreateView,
                    MembersUpdateView, 
                    MembersDeleteView, 
                    MoreMembersDetailView, 
                    IndividualMemberDetailView, 
                    IndividualMemberMoreDetailView)
from . import views


urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('members/new/', MembersCreateView.as_view(), name = 'member_create'),
    path('members/all/', MembersListView.as_view(), name='members_all'),
    path('member/me/', MembersDetailView.as_view(), name='member_detail'),
    path('member/<int:pk>/more/', MoreMembersDetailView.as_view(), name='member_more_detail'),
    path('member/<int:pk>/update/', MembersUpdateView.as_view(), name='member_update'),
    path('member/<int:pk>/delete/', MembersDeleteView.as_view(), name='member_delete'),
    path('individual/member/<int:pk>', IndividualMemberDetailView.as_view(), name='individual_member'),
    path('individual/member/<int:pk>/more/', IndividualMemberMoreDetailView.as_view(), name='individual_member_more'),
    path('about/', views.about, name='members_about')
]

children/models.py
from django.db import models
from members.models import Members


class Children(models.Model):
    GENDER_CHOICES = [
        ('Male','Male'),
        ('Female','Female'),
    ]
    
    father = models.ForeignKey(Members, on_delete=models.SET_NULL, null=True, blank=True, related_name='father_children')
    mother = models.ForeignKey(Members, on_delete=models.SET_NULL, null=True, blank=True, related_name='mother_children')
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50)
    gender = models.CharField(max_length=15, choices=GENDER_CHOICES)
    date_of_birth = models.DateField()
    

    def __str__(self):
        return f'{self.first_name} {self.middle_name}'

members/models.py
from django.db import models
from django.urls import reverse
import random
from django.contrib.auth.models import User

class Members(models.Model):
    gender_choices = [
        ('Male', 'Male'),
        ('Female', 'Female'),
    ]
    marital_status_choices = [
        ('Married', 'Married'),
        ('Unmarried', 'Unmarried'),
        ('Widow/Widower', 'Widow/Widower'),
        ('Separated', 'Separated'),
        ('Divorced', 'Divorced'),
    ]
    membership_choices = [
        ('Transfer', 'Transfer'),
        ('Baptism', 'Baptism'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=10, choices=gender_choices)
    phone_number = models.CharField(max_length=15)
    email_address = models.EmailField()
    marital_status = models.CharField(max_length=20, choices=marital_status_choices)
    membership_by = models.CharField(max_length=10, choices=membership_choices)
    occupation = models.CharField(max_length=50)
    residence_address = models.CharField(max_length=200)
    unique_id = models.CharField(max_length=6, unique=True, editable=False, null=True)

    
    @staticmethod
    def generate_unique_id():
        while True:
            unique_id = ''.join([str(random.randint(0, 9)) for _ in range(6)])
            if not Members.objects.filter(unique_id=unique_id).exists():
                return unique_id

    
    def save(self, *args, **kwargs):
        if not self.unique_id:
            self.unique_id = Members.generate_unique_id()
        super().save(*args, **kwargs)


    class Meta:
        verbose_name_plural = 'Members'

    def __str__(self):
        return self.first_name
    
    def get_absolute_url(self):
        return reverse('member_more_detail', kwargs={'pk':self.pk})

members/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
from django.db.models import Q
from . models import Members
from django.http import Http404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from children.models import Children


def home(request):
    context = {
        'members_list':Members.objects.all()
    }
    return render(request, 'members/all_members.html', context)

class CustomLoginRequiredMixin(AccessMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('/')
        
        return super().dispatch(request, *args, **kwargs)

class MembersListView(CustomLoginRequiredMixin, ListView):
    model = Members
    template_name = 'members/all_members.html'
    context_object_name = 'members_list'
    paginate_by = 2
    
    def get_queryset(self):
        query = self.request.GET.get('q', '')
        if query:
            return Members.objects.filter(
                Q(first_name__icontains=query) | Q(unique_id__icontains=query) | Q(last_name__icontains=query) | Q(middle_name__icontains=query)
            )
        return Members.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q', '')
        return context

class MembersDetailView(CustomLoginRequiredMixin, DetailView):
    model = Members
    template_name = 'members/members_detail.html'

    def get_object(self, queryset = None):
        try:
            return self.request.user.members
        except Members.DoesNotExist:
            raise Http404('No member account found for this user.')
    
    def get_queryset(self):
        return Members.objects.filter(user = self.request.user)
    
class IndividualMemberDetailView(CustomLoginRequiredMixin, DetailView):
    model = Members
    template_name = 'members/individual_member.html'

    def get_queryset(self):
        return Members.objects.filter(user = self.request.user)

class IndividualMemberMoreDetailView(CustomLoginRequiredMixin, DetailView):
    model = Members
    template_name = 'members/individual_member_more.html'

    def get_queryset(self):
        return Members.objects.filter(user = self.request.user)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        member = self.get_object()

        children_as_father = Children.objects.filter(father=member)
        children_as_mother = Children.objects.filter(mother=member)

        context['children_as_father'] = children_as_father
        context['children_as_mother'] = children_as_mother

        return context

class MoreMembersDetailView(CustomLoginRequiredMixin, DetailView):
    model = Members
    template_name = 'members/member_more_details.html'
    context_object_name = 'member'

    def test_func(self):
        return self.request.user.is_staff
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        member = self.get_object()

        children_as_father = Children.objects.filter(father=member)
        children_as_mother = Children.objects.filter(mother=member)

        context['children_as_father'] = children_as_father
        context['children_as_mother'] = children_as_mother

        return context

class MembersCreateView(CustomLoginRequiredMixin, CreateView): # capturing members details and sending an email with a unique ID
    model = Members
    fields = ['first_name', 'last_name', 'middle_name', 'gender', 'phone_number', 'email_address', 'marital_status', 'membership_by', 'occupation', 'residence_address']

    def form_valid(self, form):
        response = super().form_valid(form)
        member = self.object
        subject = 'Your Membership ID'
        message = (
            f'Dear {member.first_name}, \n\n'
            f'You have been registered with our church, Your unique ID is {member.unique_id} \n\n'
            f'Kindly use the unique ID as a username to create an account at: '
            f"http://127.0.0.1:9090/member/register/\n"
        )
        send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [member.email_address])
        return response

    def get_context_data(self, **kwargs): # Printing the appropriate header when the page is loaded
        context = super().get_context_data(**kwargs)
        context['header'] = 'Register a Member'
        return context

class MembersUpdateView(CustomLoginRequiredMixin, UpdateView):
    model = Members
    fields = ['first_name', 'last_name', 'middle_name', 'gender', 'phone_number', 'email_address', 'marital_status', 'membership_by', 'occupation', 'residence_address']

    def get_context_data(self, **kwargs): # Printing the appropriate header when the page is loaded
        context = super().get_context_data(**kwargs)
        context['header'] = "Update Member's Information"
        return context

class MembersDeleteView(CustomLoginRequiredMixin, DeleteView):
    model = Members
    success_url = reverse_lazy('members_all')

    def delete(self, request, *args, **kwargs):
        messages.success(request, "Member successfully deleted.")
        return super().delete(request, *args, **kwargs)

def about(request):
    return render(request, 'members/about.html')

def home_page(request):
    return render(request, 'members/home_page.html')

members/templates/members/about.html
{% extends 'members/base.html' %}
{% block content %}
    <h1>Hello Collince, I am proud of you this time. This is the About Page</h1>
{% endblock content %}

members/templates/members/all_members.html
{% extends 'members/base.html' %}
{% block content %}

    <div class="container mt-5">
            <a href="{% url 'member_create' %}" data-bs-toggle="tooltip" data-bs-placement="top" title="Add a member">
                <i class="bi bi-person-plus-fill" style="font-size: 2rem; text-align: right;"></i>
            </a>
            <a href="{% url 'children_list' %}" data-bs-toggle="tooltip" data-bs-placement="top" title="View Children">
                <i class="bi bi-eye" style="font-size: 2rem; text-align: right;"></i>
            </a>
            <a href="{% url 'all_contributions' %}" data-bs-toggle="tooltip" data-bs-placement="top" title="View all contributions">
                <i class="bi bi-eye-fill" style="font-size: 2rem; text-align: right;"></i>
            </a>

            <h2 class="text-center">Members List</h2>
            <form method="GET" action="" class="d-flex mb-4">
                <input type="text" name="q" class="form-control me-2" placeholder="Search by First Name or Unique ID" value="{{ query }}">
                <button class="btn btn-primary" type="submit">Search</button>
            </form>
            
            <div class="table-responsive">
                <table class="table table-secondary table-striped table-hover table-bordered">
                    <thead class="text-center">
                        <tr>
                            <th>#</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Other Names</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for member in members_list %}
                            <tr>
                                <td>{{ member.id}}</td>
                                <td>
                                    <a href="{% url 'member_more_detail' member.pk %}" data-bs-toggle="tooltip" data-bs-placement="top" title="click to view more details">
                                        {{ member.first_name }}
                                    </a>
                                </td>
                                <td>{{ member.last_name }}</td>
                                <td>{{ member.middle_name }}</td>
                            </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="5" class="text-center">No records found</td>
                                </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        <div style="text-align: center;">
            {% if is_paginated %}

            {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}

            {% endfor %}

            {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

            {% endif %}
        </div>
    </div>

        


{% endblock content %}

members/templates/members/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'members/main.css' %}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>church_app</title>
    {% endif %}
</head>
<body>
    <!-- Messages -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} text-center">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    
    <!-- Navbar -->
    {% if user.is_authenticated %}
        {% include 'partials/navbar_logged_in.html' %}
    {% endif %}

    <!-- Error Message -->
    {% if error %}
        <div class="alert alert-danger text-center" role="alert">
            {{ error }}
        </div>
    {% endif %}

    <!-- Content Wrapper for Centering -->
    <div class="content-wrapper">
        {% block content %}{% endblock content %}
    </div>

    <!-- Footer -->
    <footer class="bg-light text-center py-3">
        <p class="mb-0">© 2025 Church Management System. All Rights Reserved.</p>
    </footer>

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script>
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
    </script>
    {% if request.user.is_authenticated %}
    <script>
        const sessionTimeout = parseInt("{{ request.session.get_expiry_age|escapejs }}"); // In seconds
        console.log(`Session Timeout: ${sessionTimeout} seconds`);
        const warningTime = sessionTimeout - 60;

        setTimeout(() => {
            alert("Your session will expire in 1 minute. Please save your work.");
        }, warningTime * 1000);

        setTimeout(() => {
            window.location.href = "{% url 'logout' %}";
        }, sessionTimeout * 1000);
    </script>
    {% endif %}
</body>
</html>

members/templates/members/home_page.html
{% extends 'members/base.html' %}
{% block content %}


    <div class="welcome-container">
        <h1 class="welcome-title">Welcome to the Church Management System</h1>
        <p class="welcome-text">Please select how you would like to log in:</p>
        <div class="d-grid gap-3">
            <!-- <a href="admin-login.html" class="btn btn-login btn-admin text-white">Login as Admin</a> -->
            <a href="{% url 'user_login' %}" class="btn btn-login btn-staff text-white">Login as Staff</a>
            <a href="{% url 'member_login' %}" class="btn btn-login btn-members text-white">Login as Member</a>
        </div>
    </div>


{% endblock content %}

members/templates/members/individual_member.html
{% extends 'members/base.html' %}
{% block content %}

    <div class="container mt-5">
        <h2 class="text-center">Member Details</h2>
        <div class="table-responsive">
            <table class="table table-secondary table-striped table-hover table-bordered">
                <thead class="text-center">
                    <tr>
                        <th>#</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Other Names</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ object.id}}</td>
                        <td>
                            <a href="{% url 'individual_member_more' pk=user.members.pk %}" data-bs-toggle="tooltip" data-bs-placement="top" title="Click to view more details">
                                {{ object.first_name }}
                            </a>
                        </td>
                        <td>{{ object.last_name }}</td>
                        <td>{{ object.middle_name }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

{% endblock content %}

members/templates/members/individual_member_more.html
{% extends 'members/base.html' %}
{% block content %}

        <div class="container mt-5">
            <h2 class="text-center">Member Details</h2>
            <a href="{% url 'individual_contributions' members.pk %}" data-bs-toggle="tooltip" data-bs-placement="top" title="View contributions"> <i class="bi bi-eye" style="font-size: 2rem;"></i></a>
            <div class="table-responsive">
                <table class="table table-secondary table-striped table-hover table-bordered">
                    <thead class="text-center">
                        <tr>
                            <th>#</th>
                            <th>Unique Identifier</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Other Names</th>
                            <th>Gender</th>
                            <th>Phone Number</th>
                            <th>Email Address</th>
                            <th>Marital Status</th>
                            <th>Membership By</th>
                            <th>Occupation</th>
                            <th>Residential Address</th>
                        </tr>
                    </thead>
                    
                    <tbody>
                        <tr>
                            <td>{{ object.id}}</td>
                            <td>{{ object.unique_id }}</td>
                            <td>{{ object.first_name }}</td>
                            <td>{{ object.last_name }}</td>
                            <td>{{ object.middle_name }}</td>
                            <td>{{ object.gender }}</td>
                            <td>{{ object.phone_number }}</td>
                            <td>{{ object.email_address }}</td>
                            <td>{{ object.marital_status }}</td>
                            <td>{{ object.membership_by }}</td>
                            <td>{{ object.occupation }}</td>
                            <td>{{ object.residence_address }}</td>
                        </tr>
                    </tbody>
                    
                </table>
                
            </div>
        

            {% if children_as_father %}
                <div class="row mt-5">
                    <div class="col-12">
                        <h2 class="text-center">Children Records</h2>
                        <div class="table-responsive">
                            <table class="table table-secondary table-striped table-hover table-bordered">
                                <thead class="text-center">
                                    <tr>
                                        <th>First Name</th>
                                        <th>Middle Name</th>
                                        <th>Date of Birth</th>
                                        <th>Gender</th>
                                        <th>Mother</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for child in children_as_father %}
                                        <tr>
                                            <td>{{ child.first_name }}</td>
                                            <td>{{ child.middle_name }}</td>
                                            <td>{{ child.date_of_birth }}</td>
                                            <td>{{ child.gender }}</td>
                                            <td>{{ child.mother.first_name }} {{ child.mother.last_name }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            {% endif %}


            {% if children_as_mother %}
                <div class="row mt-5">
                    <div class="col-12">
                        <h2 class="text-center">Children Records</h2>
                        <div class="table-responsive">
                            <table class="table table-secondary table-striped table-hover table-bordered">
                                <thead class="text-center">
                                    <tr>
                                        <th>First Name</th>
                                        <th>Middle Name</th>
                                        <th>Date of Birth</th>
                                        <th>Gender</th>
                                        <th>Father</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for child in children_as_mother %}
                                        <tr>
                                            <td>{{ child.first_name }}</td>
                                            <td>{{ child.middle_name }}</td>
                                            <td>{{ child.date_of_birth }}</td>
                                            <td>{{ child.gender }}</td>
                                            <td>{{ child.father.first_name }} {{ child.father.last_name }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            {% endif %}
        </div>

{% endblock content %}

members/templates/members/members_confirm_delete.html
{% extends 'members/base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {% csrf_token %}
            <fieldset class="form-group text-center">
                <legend class="border-bottom mb-4">Delete a Member</legend>
                <h2>Are you sure you want to delete {{ object.first_name }}</h2>
            </fieldset>
            <div class="form-group text-center">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'member_more_detail' pk=object.pk %}" type="submit">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

members/templates/members/members_detail.html
{% extends 'members/base.html' %}
{% block content %}

    <div class="container mt-5">
        <h2 class="text-center">Member Details</h2>
        <div class="table-responsive">
            <table class="table table-secondary table-striped table-hover table-bordered">
                <thead class="text-center">
                    <tr>
                        <th>#</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Other Names</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ object.id}}</td>
                        <td>
                            <a href="#">
                                {{ object.first_name }}
                            </a>
                        </td>
                        <td>{{ object.last_name }}</td>
                        <td>{{ object.middle_name }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

{% endblock content %}

members/templates/members/members_form.html
{% extends 'members/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <!-- Form Card -->
            <div class="card shadow">
                <div class="card-body">
                    <h3 class="card-title text-center border-bottom pb-3">{{ header }}</h3>
                    <form method="POST" action="">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            {{ form|crispy }}
                        </fieldset>
                        <div class="form-group text-center">
                            <button class="btn btn-primary w-100" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}